server.port=8082
spring.application.name=patients-service
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/patients_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://gestionmedicale-eureka-server.railway.internal:8761/eureka
management.endpoints.web.exposure.include=*
